version: '3'
services:
  terraform:
    build: .
    volumes:
      - ${HOME}/.aws/:/root/.aws/:ro
    environment:
      AWS_DEFAULT_PROFILE: $AWS_DEFAULT_PROFILE
      VARS_FILE: "${VARS_FILE-qs.auto.tfvars}"
    command: /terraform.sh
