version: '3'
services:
  terraform:
    build: terraform
    volumes:
      - ${HOME}/.aws/:/root/.aws/:ro
      - /tmp/:/tmp/
    environment:
      PROFILE: $AWS_DEFAULT_PROFILE
      BUILD: $BUILD
  apex:
    build: apex
    volumes:
      - ${HOME}/.aws/:/root/.aws/:ro
      - /tmp/:/tmp/
    environment:
      PROFILE: $AWS_DEFAULT_PROFILE
      BUILD: $BUILD
